matrix:
  include:
    - language: go
      sudo: false
      go: "1.10"
      install:
        - go get -v -u github.com/golang/dep/cmd/dep
        - export PATH=$PATH:$GOPATH/bin
        - make vendor
        - export ACI_SNAT_NAMESPACE=default
        - export ACI_SNAGLOBALINFO_NAME=snatglobalinfo
      script:
        - make goinstall
        - go test -cover github.com/noironetworks/snat-operator/pkg/controller/snatPolicy
        - go test -cover github.com/noironetworks/snat-operator/pkg/controller/snatlocalinfo
        - go test -cover github.com/noironetworks/snat-operator/pkg/controller/snatglobalinfo

