matrix:
  include:
    - language: go
      sudo: false
      go: "1.10"
      install:
        - go get -v -u github.com/golang/dep/cmd/dep
        - export PATH=$PATH:$GOPATH/bin
        - make vendor
      script:
        - make goinstall
        - make check
