apiVersion: aci.snat/v1
kind: SnatPolicy
metadata:
  name: examplesnatpolicy
spec:
  snatIp: 
    - 
      10.20.30.40/30
  selector:
    namespace: foo
    labels:
       -
         key: name
         value: development

  portRange:
     - 
      end: 15000
      start: 5000
    # - 
    #   end: 20000
    #   start: 10001
    # - 
    #   end: 65000
    #   start: 20001

