apiVersion: apps/v1
kind: Deployment
metadata:
  name: snat-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: snat-operator
  template:
    metadata:
      labels:
        name: snat-operator
    spec:
      serviceAccountName: snat-operator
      containers:
        - name: snat-operator
          # Replace this with the built image name
          image: jayaramksv/snat-operator:sep-24
          command:
          - snat-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "snat-operator"
